---

- name: brew cask install osxfuse
  homebrew_cask:
    name: osxfuse
    state: present
  become: true
  become_user: "{{ boxafe_homebrew_user }}"
  tags:
    - boxafe
  when: ansible_pkg_mgr == 'homebrew'

- name: brew install encfs
  homebrew:
    name: encfs
    state: present
  become: true
  become_user: "{{ boxafe_homebrew_user }}"
  tags:
    - boxafe
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
